import type { Metadata } from 'next'

import { Lexend } from 'next/font/google'

import { ConvexClientProvider } from './components/convex-client-provider'

import './globals.scss'

export const metadata: Metadata = {
	title: 'Wodify',
	description: 'Generated by create next app',
}

const lexend = Lexend({ subsets: ['latin'] })

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={lexend.className}>
				<ConvexClientProvider>{children}</ConvexClientProvider>
			</body>
		</html>
	)
}
